### ISSUE TITLE
Bluemix - getRecent() getting app logs failing with RangeError: Illegal offset

### ISSUE THREAD

**Issue by jamesjong** [IBM-Bluemix/cf-nodejs-client#25]
getRecent() is failing when attempting to retrieve logs for any Bluemix application that contains recent logs.  The current mocha test for logs (https://github.com/IBM-Bluemix/cf-nodejs-client/blob/master/test/lib/model/metrics/LogTests.js#L54) pass because the test app returns an empty log (i.e. there were no recent logs).  I modified the test to point to a Bluemix app that had recent logs and the mocha test fails (result is below).
cc: @chambrid

  1) Cloud foundry Logs The platform returns Logs:
     AssertionError: expected [RangeError: Illegal offset: 0 <= 127 (+1) <= 53] to equal 'No App'
      at test/lib/model/metrics/LogTests.js:83:31
      at tryCatcher (node_modules/bluebird/js/release/util.js:11:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:489:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:546:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:591:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:670:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:129:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:139:10)
      at Immediate.Async.drainQueues [as _onImmediate](node_modules/bluebird/js/release/async.js:16:14)

**Comment by jsloyer** [comment]
@nsand thoughts on this one?

**Comment by nsand** [comment]
I was taking a look at this with James this morning. Nothing really stood out to me as to why it was failing after a long stretch of working properly.

The protobuf decoding seems to not like something about one or more of the buffers that we're passing to it. And the cryptic messages don't help too much. When I was originally implementing this, I was getting similar messages because too much of the multipart message was being trimmed off (ASCII deception).

I'll keep taking a look.

**Comment by nsand** [comment]
@jsloyer Opened #26 to address this. Looks like a line got removed that ended up causing the log body to be parsed as a string instead of as a Buffer.

**Comment by jsloyer** [comment]
I merged in #26. I'll bump the version and publish.

**Comment by jsloyer** [comment]
@jamesjong can you verify this is fixed in 0.13.22?

**Comment by jamesjong** [comment]
@jsloyer I tested on 0.13.22 and it's fixed.  Thanks!
